import{initializeApp}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";import{getFirestore,collection,onSnapshot,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";import{firebaseConfig}from"./firebase-config.js";import{starterMenu}from"./menu-data.js";
const $=s=>document.querySelector(s);let db=null,menu=[...starterMenu],cart={},category="All";const table=Math.min(25,Math.max(1,Number(new URLSearchParams(location.search).get("table"))||1));$("#tableLabel").textContent=`Table ${String(table).padStart(2,"0")}`;
const icon=c=>c==="Coffee"?"☕":c==="Pizza"?"🍕":c==="Burgers"?"🍔":c==="Momos"?"🥟":c==="Desserts"?"🍨":"🥣";
function render(){const q=$("#search").value.toLowerCase(),cats=["All",...new Set(menu.map(i=>i.category))];$("#categories").innerHTML=cats.map(c=>`<button class="${c===category?"active":""}" data-cat="${c}">${c}</button>`).join("");const shown=menu.filter(i=>i.available!==false&&(category==="All"||i.category===category)&&i.name.toLowerCase().includes(q));$("#categoryTitle").textContent=category==="All"?"Our favourites":category;$("#itemCount").textContent=`${shown.length} items`;$("#menuGrid").innerHTML=shown.map(i=>`<article class="food-card"><div class="food-art">${icon(i.category)}${i.tag?`<em>${i.tag}</em>`:""}</div><div><small>▣ PURE VEG</small><h3>${i.name}</h3><p>Freshly prepared with our signature cafe flavours.</p><footer><strong>₹${i.price}</strong>${cart[i.id]?`<div class="stepper"><button data-minus="${i.id}">−</button><b>${cart[i.id]}</b><button data-plus="${i.id}">+</button></div>`:`<button data-add="${i.id}">＋ ADD</button>`}</footer></div></article>`).join("");renderCartButton()}
function renderCartButton(){const count=Object.values(cart).reduce((a,b)=>a+b,0),total=menu.reduce((s,i)=>s+(cart[i.id]||0)*i.price,0);$("#viewCart").classList.toggle("hidden",!count);$("#viewCart").innerHTML=`<span>${count} item(s) · ₹${total}</span><b>View order →</b>`}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.cat){category=b.dataset.cat;render()}for(const key of["add","plus","minus"]){if(b.dataset[key]){const id=b.dataset[key];cart[id]=Math.max(0,(cart[id]||0)+(key==="minus"?-1:1));render()}}if(b.id==="viewCart")openCart();if(b.dataset.close!==undefined)$("#cartModal").classList.add("hidden")});$("#search").addEventListener("input",render);
function openCart(){const rows=menu.filter(i=>cart[i.id]);$("#cartTable").textContent=`TABLE ${String(table).padStart(2,"0")}`;$("#cartLines").innerHTML=rows.map(i=>`<div class="cart-line"><span>${cart[i.id]}× ${i.name}</span><b>₹${cart[i.id]*i.price}</b></div>`).join("");const total=rows.reduce((s,i)=>s+cart[i.id]*i.price,0);$("#cartTotal").textContent=`₹${total}`;$("#placeOrder").textContent=`Place order · ₹${total}`;$("#cartModal").classList.remove("hidden")}
let orderSending=false;$("#placeOrder").onclick=async()=>{if(orderSending)return;const items=menu.filter(i=>cart[i.id]).map(i=>({id:i.id,name:i.name,price:i.price,qty:cart[i.id]})),total=items.reduce((s,i)=>s+i.price*i.qty,0);if(!items.length)return;if(!db){$("#orderMessage").textContent="Live order connect nahi hai. Cafe owner se contact karein.";return}orderSending=true;const orderBtn=$("#placeOrder");orderBtn.disabled=true;orderBtn.textContent="Sending order…";$("#orderMessage").textContent="Please wait, order send ho raha hai…";try{const placed=await addDoc(collection(db,"orders"),{table,items,total,note:$("#orderNote").value.trim(),status:"New",discount:0,paymentMode:null,createdAt:serverTimestamp()});cart={};$("#orderNote").value="";$("#orderMessage").textContent="";$("#cartModal").classList.add("hidden");$("#successTable").textContent=`TABLE ${String(table).padStart(2,"0")}`;$("#successOrder").textContent=`Order #${placed.id.slice(-6).toUpperCase()}`;$("#successModal").classList.remove("hidden");render()}catch(e){$("#orderMessage").textContent="Order send nahi hua. Internet check karke dobara try karein.";orderBtn.disabled=false;orderBtn.textContent=`Place order · ₹${total}`;orderSending=false}};$("#doneOrder").onclick=()=>{$("#successModal").classList.add("hidden");orderSending=false};

// Food items ko Firebase setup se pehle bhi turant show karein.
render();
const firebaseReady=firebaseConfig.apiKey&&!firebaseConfig.apiKey.startsWith("PASTE_")&&firebaseConfig.projectId&&!firebaseConfig.projectId.startsWith("PASTE_");
if(firebaseReady){try{const app=initializeApp(firebaseConfig);db=getFirestore(app);onSnapshot(collection(db,"menu"),snap=>{menu=snap.empty?[...starterMenu]:snap.docs.map(d=>({id:d.id,...d.data()}));render()},()=>{menu=[...starterMenu];render()})}catch(e){console.warn("Firebase setup incomplete; starter menu is active.",e)}}
