// ============================================================
// THE HUTS CAFE - MASTER MENU DATA
// ============================================================
// To change an image, paste a DIRECT image address inside image: "..."
// Example: image: "https://example.com/my-food-photo.jpg"
// Google Images: use "Copy image address", not "Copy link address".
// Keep image: "" if you want the category emoji fallback.

const IMAGES = {
  hotCoffee:
    "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=82",
  coldCoffee:
    "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=82",
  tea: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=82",
  coldDrink:
    "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=82",
  shake:
    "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=900&q=82",
  burger:
    "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=82",
  sandwich:
    "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=82",
  wrap: "https://images.unsplash.com/photo-1562059390-a761a084768e?auto=format&fit=crop&w=900&q=82",
  momos:
    "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=900&q=82",
  pizza:
    "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=82",
  pasta:
    "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=82",
  fries:
    "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=82",
  quickBites:
    "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=900&q=82",
  soup: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=900&q=82",
  dessert:
    "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=82",
  iceCream:
    "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=900&q=82",
};

export const starterMenu = [
  // -------------------- COFFEE (8) --------------------
  {
    id: "coffee-1",
    name: "Hot Americano",
    category: "Coffee",
    price: 69,
    available: true,
    image: IMAGES.hotCoffee,
  },
  {
    id: "coffee-2",
    name: "Cappuccino",
    category: "Coffee",
    price: 79,
    available: true,
    tag: "Popular",
    image: IMAGES.hotCoffee,
  },
  {
    id: "coffee-3",
    name: "Espresso",
    category: "Coffee",
    price: 69,
    available: true,
    image: IMAGES.hotCoffee,
  },
  {
    id: "coffee-4",
    name: "Double Espresso",
    category: "Coffee",
    price: 79,
    available: true,
    image: IMAGES.hotCoffee,
  },
  {
    id: "coffee-5",
    name: "Iced Brew",
    category: "Coffee",
    price: 79,
    available: true,
    image: IMAGES.coldCoffee,
  },
  {
    id: "coffee-6",
    name: "Cold Coffee",
    category: "Coffee",
    price: 89,
    available: true,
    tag: "Bestseller",
    image: IMAGES.coldCoffee,
  },
  {
    id: "coffee-7",
    name: "Brownie Cold Coffee",
    category: "Coffee",
    price: 149,
    available: true,
    image: IMAGES.coldCoffee,
  },
  {
    id: "coffee-8",
    name: "Oreo Cold Coffee",
    category: "Coffee",
    price: 149,
    available: true,
    tag: "Popular",
    image: IMAGES.coldCoffee,
  },

  // -------------------- TEA & COLD BEVERAGES (8) --------------------
  {
    id: "beverage-1",
    name: "Regular Tea",
    category: "Beverages",
    price: 30,
    available: true,
    image: IMAGES.tea,
  },
  {
    id: "beverage-2",
    name: "Ginger Tea",
    category: "Beverages",
    price: 40,
    available: true,
    image: IMAGES.tea,
  },
  {
    id: "beverage-3",
    name: "Masala Tea",
    category: "Beverages",
    price: 40,
    available: true,
    tag: "Popular",
    image: IMAGES.tea,
  },
  {
    id: "beverage-4",
    name: "Lemon Honey Tea",
    category: "Beverages",
    price: 40,
    available: true,
    image: IMAGES.tea,
  },
  {
    id: "beverage-5",
    name: "Fresh Lime Soda",
    category: "Beverages",
    price: 79,
    available: true,
    image: IMAGES.coldDrink,
  },
  {
    id: "beverage-6",
    name: "Virgin Mint Mojito",
    category: "Beverages",
    price: 99,
    available: true,
    tag: "Refreshing",
    image: IMAGES.coldDrink,
  },
  {
    id: "beverage-7",
    name: "Blue Lagoon",
    category: "Beverages",
    price: 99,
    available: true,
    image: IMAGES.coldDrink,
  },
  {
    id: "beverage-8",
    name: "Watermelon Cooler",
    category: "Beverages",
    price: 99,
    available: true,
    image: IMAGES.coldDrink,
  },

  // -------------------- SHAKES (6) --------------------
  {
    id: "shake-1",
    name: "Chocolate Shake",
    category: "Shakes",
    price: 99,
    available: true,
    tag: "Popular",
    image: IMAGES.shake,
  },
  {
    id: "shake-2",
    name: "Oreo Shake",
    category: "Shakes",
    price: 109,
    available: true,
    tag: "Bestseller",
    image: IMAGES.shake,
  },
  {
    id: "shake-3",
    name: "KitKat Shake",
    category: "Shakes",
    price: 119,
    available: true,
    image: IMAGES.shake,
  },
  {
    id: "shake-4",
    name: "Vanilla Shake",
    category: "Shakes",
    price: 89,
    available: true,
    image: IMAGES.shake,
  },
  {
    id: "shake-5",
    name: "Mango Shake",
    category: "Shakes",
    price: 99,
    available: true,
    image: IMAGES.shake,
  },
  {
    id: "shake-6",
    name: "Strawberry Shake",
    category: "Shakes",
    price: 99,
    available: true,
    image: IMAGES.shake,
  },

  // -------------------- BURGERS (6) --------------------
  {
    id: "burger-1",
    name: "Aloo Tikki Burger",
    category: "Burgers",
    price: 59,
    available: true,
    image: IMAGES.burger,
  },
  {
    id: "burger-2",
    name: "Veg Supreme Burger",
    category: "Burgers",
    price: 69,
    available: true,
    image: IMAGES.burger,
  },
  {
    id: "burger-3",
    name: "Cheese Tikki Burger",
    category: "Burgers",
    price: 79,
    available: true,
    tag: "Bestseller",
    image: IMAGES.burger,
  },
  {
    id: "burger-4",
    name: "Paneer Tikki Burger",
    category: "Burgers",
    price: 99,
    available: true,
    image: IMAGES.burger,
  },
  {
    id: "burger-5",
    name: "Peri Peri Burger",
    category: "Burgers",
    price: 109,
    available: true,
    image: IMAGES.burger,
  },
  {
    id: "burger-6",
    name: "Double Cheese Burger",
    category: "Burgers",
    price: 129,
    available: true,
    tag: "Chef's Pick",
    image: IMAGES.burger,
  },

  // -------------------- SANDWICHES & WRAPS (8) --------------------
  {
    id: "sandwich-1",
    name: "Veg Grilled Sandwich",
    category: "Sandwiches & Wraps",
    price: 69,
    available: true,
    image: IMAGES.sandwich,
  },
  {
    id: "sandwich-2",
    name: "Veg Cheese Grilled Sandwich",
    category: "Sandwiches & Wraps",
    price: 89,
    available: true,
    image: IMAGES.sandwich,
  },
  {
    id: "sandwich-3",
    name: "Tandoori Sandwich",
    category: "Sandwiches & Wraps",
    price: 109,
    available: true,
    tag: "Popular",
    image: IMAGES.sandwich,
  },
  {
    id: "sandwich-4",
    name: "Paneer Tikka Sandwich",
    category: "Sandwiches & Wraps",
    price: 129,
    available: true,
    image: IMAGES.sandwich,
  },
  {
    id: "wrap-1",
    name: "Veg Wrap",
    category: "Sandwiches & Wraps",
    price: 79,
    available: true,
    image: IMAGES.wrap,
  },
  {
    id: "wrap-2",
    name: "Mexican Wrap",
    category: "Sandwiches & Wraps",
    price: 99,
    available: true,
    image: IMAGES.wrap,
  },
  {
    id: "wrap-3",
    name: "Paneer Tikka Wrap",
    category: "Sandwiches & Wraps",
    price: 119,
    available: true,
    tag: "Bestseller",
    image: IMAGES.wrap,
  },
  {
    id: "wrap-4",
    name: "Cheesy Corn Wrap",
    category: "Sandwiches & Wraps",
    price: 119,
    available: true,
    image: IMAGES.wrap,
  },

  // -------------------- MOMOS (6) --------------------
  {
    id: "momos-1",
    name: "Steam Momos (6 pcs)",
    category: "Momos",
    price: 69,
    available: true,
    image: IMAGES.momos,
  },
  {
    id: "momos-2",
    name: "Fried Momos (6 pcs)",
    category: "Momos",
    price: 79,
    available: true,
    image: IMAGES.momos,
  },
  {
    id: "momos-3",
    name: "Kurkure Momos (6 pcs)",
    category: "Momos",
    price: 99,
    available: true,
    tag: "Popular",
    image: IMAGES.momos,
  },
  {
    id: "momos-4",
    name: "Paneer Momos (6 pcs)",
    category: "Momos",
    price: 99,
    available: true,
    image: IMAGES.momos,
  },
  {
    id: "momos-5",
    name: "Tandoori Momos (6 pcs)",
    category: "Momos",
    price: 119,
    available: true,
    tag: "Chef's Pick",
    image: IMAGES.momos,
  },
  {
    id: "momos-6",
    name: "Gravy Momos (6 pcs)",
    category: "Momos",
    price: 129,
    available: true,
    image: IMAGES.momos,
  },

  // -------------------- PIZZA (8) --------------------
  {
    id: "pizza-1",
    name: "Onion Pizza",
    category: "Pizza",
    price: 129,
    available: true,
    image: IMAGES.pizza,
  },
  {
    id: "pizza-2",
    name: "Margherita Pizza",
    category: "Pizza",
    price: 139,
    available: true,
    tag: "Popular",
    image: IMAGES.pizza,
  },
  {
    id: "pizza-3",
    name: "OTC Pizza",
    category: "Pizza",
    price: 159,
    available: true,
    image: IMAGES.pizza,
  },
  {
    id: "pizza-4",
    name: "Corn Pizza",
    category: "Pizza",
    price: 159,
    available: true,
    image: IMAGES.pizza,
  },
  {
    id: "pizza-5",
    name: "Farm House Pizza",
    category: "Pizza",
    price: 189,
    available: true,
    image: IMAGES.pizza,
  },
  {
    id: "pizza-6",
    name: "Paneer Tikka Pizza",
    category: "Pizza",
    price: 220,
    available: true,
    tag: "Bestseller",
    image: IMAGES.pizza,
  },
  {
    id: "pizza-7",
    name: "Peri Peri Paneer Pizza",
    category: "Pizza",
    price: 250,
    available: true,
    image: IMAGES.pizza,
  },
  {
    id: "pizza-8",
    name: "The Huts Special Pizza",
    category: "Pizza",
    price: 350,
    available: true,
    tag: "Chef's Pick",
    image: IMAGES.pizza,
  },

  // -------------------- PASTA (6) --------------------
  {
    id: "pasta-1",
    name: "Red Sauce Pasta",
    category: "Pasta",
    price: 139,
    available: true,
    image: IMAGES.pasta,
  },
  {
    id: "pasta-2",
    name: "White Sauce Pasta",
    category: "Pasta",
    price: 149,
    available: true,
    tag: "Popular",
    image: IMAGES.pasta,
  },
  {
    id: "pasta-3",
    name: "Mix Sauce Pasta",
    category: "Pasta",
    price: 159,
    available: true,
    image: IMAGES.pasta,
  },
  {
    id: "pasta-4",
    name: "Cheesy Penne Pasta",
    category: "Pasta",
    price: 169,
    available: true,
    image: IMAGES.pasta,
  },
  {
    id: "pasta-5",
    name: "Peri Peri Pasta",
    category: "Pasta",
    price: 169,
    available: true,
    image: IMAGES.pasta,
  },
  {
    id: "pasta-6",
    name: "The Huts Special Pasta",
    category: "Pasta",
    price: 179,
    available: true,
    tag: "Chef's Pick",
    image: IMAGES.pasta,
  },

  // -------------------- QUICK BITES (8) --------------------
  {
    id: "quick-1",
    name: "Salted Fries",
    category: "Quick Bites",
    price: 59,
    available: true,
    image: IMAGES.fries,
  },
  {
    id: "quick-2",
    name: "Peri Peri Fries",
    category: "Quick Bites",
    price: 89,
    available: true,
    tag: "Popular",
    image: IMAGES.fries,
  },
  {
    id: "quick-3",
    name: "Cheese Fries",
    category: "Quick Bites",
    price: 99,
    available: true,
    image: IMAGES.fries,
  },
  {
    id: "quick-4",
    name: "Chilli Potato",
    category: "Quick Bites",
    price: 110,
    available: true,
    image: IMAGES.quickBites,
  },
  {
    id: "quick-5",
    name: "Honey Chilli Potato",
    category: "Quick Bites",
    price: 129,
    available: true,
    image: IMAGES.quickBites,
  },
  {
    id: "quick-6",
    name: "Stuffed Garlic Bread (5 pcs)",
    category: "Quick Bites",
    price: 129,
    available: true,
    image: IMAGES.quickBites,
  },
  {
    id: "quick-7",
    name: "Cheese Patties",
    category: "Quick Bites",
    price: 59,
    available: true,
    image: IMAGES.quickBites,
  },
  {
    id: "quick-8",
    name: "Veg Masala Patties",
    category: "Quick Bites",
    price: 49,
    available: true,
    image: IMAGES.quickBites,
  },

  // -------------------- SOUPS (3) --------------------
  {
    id: "soup-1",
    name: "Tomato Soup",
    category: "Soups",
    price: 79,
    available: true,
    image: IMAGES.soup,
  },
  {
    id: "soup-2",
    name: "Manchow Soup",
    category: "Soups",
    price: 99,
    available: true,
    tag: "Popular",
    image: IMAGES.soup,
  },
  {
    id: "soup-3",
    name: "Sweet Corn Soup",
    category: "Soups",
    price: 99,
    available: true,
    image: IMAGES.soup,
  },

  // -------------------- DESSERTS (5) --------------------
  {
    id: "dessert-1",
    name: "Vanilla Ice Cream (2 scoop)",
    category: "Desserts",
    price: 49,
    available: true,
    image: IMAGES.iceCream,
  },
  {
    id: "dessert-2",
    name: "Chocolate Ice Cream (2 scoop)",
    category: "Desserts",
    price: 59,
    available: true,
    image: IMAGES.iceCream,
  },
  {
    id: "dessert-3",
    name: "Brownie",
    category: "Desserts",
    price: 49,
    available: true,
    image: IMAGES.dessert,
  },
  {
    id: "dessert-4",
    name: "Brownie with Hot Chocolate",
    category: "Desserts",
    price: 99,
    available: true,
    image: IMAGES.dessert,
  },
  {
    id: "dessert-5",
    name: "Brownie with Ice Cream",
    category: "Desserts",
    price: 99,
    available: true,
    tag: "Bestseller",
    image: IMAGES.dessert,
  },
];
